### ISSUE TITLE
Unable to run with interesting statement

### ISSUE THREAD

**Issue by ei8htb8ll** [RANKTW/Discord-Token-Checker#26]
Installed the latest version of Java 1.8.0_321 on the Java site, have it enabled in the Java panel in the Control Panel of Windows. Put the DTC files in a folder called DMDGO on the desktop, opened CMD, navigated to DMDGO, typed "start.bat" and this is the message I'm getting. I have no other versions of Java installed at all and the one that I do have, I enabled. This installed version of Java is a 64bit version. Any idea what's happening here?

Trying to start program with Java 16.0.1

Recommend Java version is 1.8.0←[0;31m
 Using any other version may not work , please download the latest version from https://www.java.com/en/download/
←[0m
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
        at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
        at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1126)
        at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1107)
        at java.base/java.lang.reflect.Field.get(Field.java:419)
        at b.I_.eG(Unknown Source)
        at b.zV.<clinit>(sPgGAxRhd9ir4uymXGppBg==:33861)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at b.I_.Yq(Unknown Source)
        at b.I_.NG(Unknown Source)
        at b.wN.Lx(n4rp80TlpTZHV8m2OTis4ku35uHW0Bs7:33987)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at b.I_.JG(Unknown Source)
        at b.I_.rC(Unknown Source)
        at net.ranktw.discord.Control.main(1ZhvGfEglSs=:33312)
Caused by: java.lang.IllegalAccessException: Can not set static final b.h_ field b.h_.VU to b.R_
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
        at java.base/jdk.internal.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
        at java.base/java.lang.reflect.Field.set(Field.java:793)
        at b.I_.Tq(Unknown Source)
        at b.h_.<clinit>(sPgGAxRhd9ir4uymXGppBg==:33506)
        ... 23 more

**Comment by RANKTW** [comment]
try open the CMD then type `java -version` to check what version you are using in runtime

**Comment by ei8htb8ll** [comment]
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

I don't understand how this is when I literally just downloaded the version
1.8 version you provided in your link.

**Comment by RANKTW** [comment]
try uninstall it
