### ISSUE TITLE
Issues with starting!

### ISSUE THREAD

**Issue by Impto-dev** [RANKTW/Discord-Token-Checker#30]
I have java 8 and java 18, issue is posted below 

ISSUES!

Trying to start program with Java 18

Recommend Java version is 1.8.0
 Using any other version may not work , please download the latest version from https://www.java.com/en/download/

Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:140)
        at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:176)
        at java.base/java.lang.reflect.Field.acquireOverrideFieldAccessor(Field.java:1184)
        at java.base/java.lang.reflect.Field.getOverrideFieldAccessor(Field.java:1153)
        at java.base/java.lang.reflect.Field.get(Field.java:428)
        at b.I_.eG(Unknown Source)
        at b.zV.<clinit>(sPgGAxRhd9ir4uymXGppBg==:33861)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
        at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:192)
        at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:719)
        at java.base/java.lang.reflect.Method.invoke(Method.java:574)
        at b.I_.Yq(Unknown Source)
        at b.I_.NG(Unknown Source)
        at b.wN.Lx(n4rp80TlpTZHV8m2OTis4ku35uHW0Bs7:33987)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at b.I_.JG(Unknown Source)
        at b.I_.rC(Unknown Source)
        at net.ranktw.discord.Control.main(1ZhvGfEglSs=:33312)
Caused by: java.lang.IllegalAccessException: Can not set static final b.h_ field b.h_.VU to b.R_
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwFinalFieldIllegalAccessException(FieldAccessorImpl.java:137)
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwFinalFieldIllegalAccessException(FieldAccessorImpl.java:141)
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:103)
        at java.base/java.lang.reflect.Field.set(Field.java:820)
        at b.I_.Tq(Unknown Source)
        at b.h_.<clinit>(sPgGAxRhd9ir4uymXGppBg==:33506)
        ... 25 more

**Comment by Impto-dev** [comment]
My Bad Wrong Java Path!
