### ISSUE TITLE
Stuck on start

### ISSUE THREAD

**Issue by Crysiz2631** [RANKTW/Discord-Token-Checker#58]
`Trying to start program with Java 11.0.16.1

Recommend Java version is 1.8.0
 Using any other version may not work , please download the latest version from https://www.java.com/en/download/

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by l.?? (file:/C:/Users/chris/OneDrive/Desktop/heck/DTC%20TOKEN/new/DTC.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of l.??
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[22:03:18] Fetching chrome version at versionhistory.googleapis.com
/fonts/OpenSans-Bold.ttf Font is null, java.io.IOException: Problem reading font data.
Loading Settings
Saving Default Settings
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException
        at java.base/java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(ThreadPoolExecutor.java:1535)
        at l.??.<init>(+oOPt7ZaerM=:43408)
        at l.??.??(+oOPt7ZaerM=:34402)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by Crysiz2631** [comment]
i got it to work
