### ISSUE TITLE
/fonts/OpenSans-Bold.ttf Font null, Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by lxntagram** [RANKTW/Discord-Token-Checker#60]
```
Gtk-Message: 00:42:16.945: Failed to load module "canberra-gtk-module"
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by l.ڪا (file:/home/sme/%eb%8b%a4%ec%9a%b4%eb%a1%9c%eb%93%9c/DTC/DTC.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of l.ڪا
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[00:42:17] Fetching chrome version at versionhistory.googleapis.com
/fonts/OpenSans-Bold.ttf Font is null, java.io.IOException: Problem reading font data.
Loading Settings
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(ThreadPoolExecutor.java:1535)
	at l.مب.<init>(+oOPt7ZaerM=:43408)
	at l.مب.ۇؠ(+oOPt7ZaerM=:34402)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[00:42:18] Chrome Version : 116
[00:42:18] Browser Version : 116.0.0.0
[00:42:18] Fetching discord build number at discord.com
[00:42:18] Successfully grabbed latest build number [225093]
[00:42:18] Discord API Version : v9
[00:42:18] UserAgent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
```
Here's the log, after it the GUI doesn't appear :(
Running on ubuntu 22.04.
I tried download and put 'OpenSans-Bold.ttf' in /fonts/ and run it in root but failed.
Started DTC.jar with `java -jar DTC.jar`

**Comment by lxntagram** [comment]
it says `openjdk version "11.0.20.1" 2023-08-24 `

**Comment by RANKTW** [comment]
wrong java version, uninstall it and download from https://www.java.com/en/download/

**Comment by lxntagram** [comment]
Worked perfectly. Thanks you for replying
